### PR TITLE
Revised contrast test requirements

### LINKED ISSUE #1203: Contrast test: Modify "How to test" for requirement 1: UI components
## Describe the bug
Clarify step 2a by adding text.

Current:
> 1. In the target page, examine each highlighted element in each of the following states:
Normal
Focused
Mouseover
Selected (if applicable)
2. In each state, use Accessibility Insights for Windows (or if you are testing on a Mac, the Colour Contrast Analyser) to verify that the following visual presentations (if implemented) have a contrast ratio of at least 3:1 against the adjacent background:
Any visual effect that indicates state
Any visual boundary that indicates the component's clickable area

Proposed: 
>1.	In the target page, examine each highlighted element in its normal state (not disabled or selected, no mouseover or input focus).
2.	Use Accessibility Insights for Windows (or if you are testing on a Mac, the Colour Contrast Analyser) to verify that the following visual presentations (if implemented) have a contrast ratio of at least 3:1 against the adjacent background:
a.	Any visual boundary that indicates the component's clickable area
b.	Any visual effect that indicates the component is in its normal state

**To Reproduce**

1. Go to the **Contrast** test.
2. Select the first requirement.
3. See the "How to test" content

## Are you willing to submit a PR?

No.

## Did you search for similar existing issues?

Yes.

### PR DESCRIPTION
**Pull request by isadu**
#### Description of changes

Updates text in "Contrast" test steps "UI components" and "State changes" to the proposed text in #1203 and #1204 (one typo fixed: differente -> different). "Info & examples" is removed from the "State changes" page by setting the infoAndExamples in `src/content/test/contrast/state-changes.tsx` to `undefined`.

image
image

Text for "State changes" removed from Test Guidance (`src/content/test/contrast/guidance.tsx`). 

image

#### Pull request checklist

- [x] Addresses an existing issue: Fixes #1203 and #1204 
- [ ] Added relevant unit test for your changes. (`yarn test`)
- [x] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [x] Ran precheckin (`yarn precheckin`)
- [x] (UI changes only) Added screenshots/GIFs to description above
- [ ] (UI changes only) Verified usability with NVDA/JAWS

### CODE REVIEW

File: src/assessments/contrast/test-steps/state-changes.tsx [hunk 1]
```diff
@@ -17,28 +17,37 @@ import { ReportInstanceField } from '../../types/report-instance-field';
...
                 </ol>
             </li>
             <li>
-                If any component indicates state changes solely by a change of color, use <WindowsContrastCheckerAppLink /> to verify that
-                the contrast ratio between different states is at least 3:1. (If you are testing on a Mac, you can use the{' '}
-                <MacContrastCheckerAppLink />
-                .)
+                Use <WindowsContrastCheckerAppLink /> (or if you are testing on a Mac, the <MacContrastCheckerAppLink />) to verify that the
+                visual indicator has a contrast ratio of at least 3:1 against the adjacent background.
+            </li>
```
Comment (dbjorge) [inline src/assessments/contrast/test-steps/state-changes.tsx]: This code matches the suggested new text from #1204, but in most of the similar "How to test" text from other requirements, I think an "Exception" block like this is usually written as a second paragraph within the preceding `<li>`, not as a separate `<li>`. @ferBonnin / @LiLoDavis, should we collapse the `Exception:` paragraph into the same `<li>` as the `Use Accessibility Insights for Windows` one for consistency?

**Comment by dbjorge** [comment]
Changes look great to me besides the minor clarification request for Fer/Lisa Louise. Thanks for the contribution, @isadu!

File: src/assessments/contrast/test-steps/state-changes.tsx (hunk 1 above)
Comment (ferBonnin) [reply src/assessments/contrast/test-steps/state-changes.tsx]: @dbjorge agree. This should be within the <li> and not as a separate list item.
Thanks for the contribution Isadu!
