### PR TITLE
fix: list structure is incorrect

### LINKED ISSUE #2037: Accessibility issue on 2.14.0 Insiders (validation bug)
## Describe the bug

Found an a11y issue while validating Insiders 2.5.0 version with `description: "Ensures that lists are structured correctly"`.
Find attached screenshot to see the issue.

**To Reproduce**

1. Go to any website
2. Activate the extension and go to assessment and click on  `12 Page Navigation`
3. open dev tools and run `A11YSelfValidator.validate()`

## Expected behavior

A11ySelfvalidator should return [] on Assessment details view page.

## Screenshots
MicrosoftTeams-image

## Context (please complete the following information)

- OS Name & Version: macOS Catalina
- AI-Web Version & Environment: 2.14.0 Insider
- Browser Version: Google Chrome Version 80.0.3987.66 (Official Build) beta (64-bit)
- Target Page: https://www.washington.edu/accesscomputing/AU/before.html

## Are you willing to submit a PR?
Yes.

## Did you search for similar existing issues?
Yes

### PR DESCRIPTION
**Pull request by smoralesd**
#### Description of changes

Fixes #2037 

**Notes** this is a html structure change only, there is no visual change. The new list passes A11Y self-validation.

picture of how to test instructions for multiple ways requirement

#### Pull request checklist
- [x] Addresses an existing issue: #2037 
- [x] Ran `yarn fastpass`
- [ ] Added/updated relevant unit test(s) (and ran `yarn test`)
- [ ] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [x] PR title *AND* final merge commit title both start with a semantic tag (`fix:`, `chore:`, `feat(feature-name):`, `refactor:`). Check workflow guide at: `<rootDir>/docs/workflow.md`
- [x] (UI changes only) Added screenshots/GIFs to description above
- [ ] (UI changes only) Verified usability with NVDA/JAWS

### CODE REVIEW

File: src/assessments/page/test-steps/general-navigation.tsx [hunk 1]
```diff
@@ -16,34 +16,42 @@ const generalNavigationDescription: JSX.Element = (
...
             </li>
-            <ol>
-                <li>Site maps</li>
-                <li>Site search</li>
-                <li>Tables of contents</li>
-                <li>Navigation menus or dropdowns</li>
-                <li>Navigation trees</li>
-                <li>Links between pages</li>
-            </ol>
+            <li>
```
Comment (peterdur) [inline src/assessments/page/test-steps/general-navigation.tsx]: The extra `</li><li>` pair at 44/45 is causing a blank list item to appear:
image

Comment (smoralesd) [reply src/assessments/page/test-steps/general-navigation.tsx]: Good catch
