### PR TITLE
[Bug Fix] Switcher change between Assessment and FastPass doesn't announce changes correctly

### LINKED ISSUE #570: Switcher Dropdown list to change between Assessment and FastPass doesn't announce changes
## Describe the bug

**To Reproduce**
0.- turn on NVDA
1. Go to https://www.washington.edu/accesscomputing/AU/before.html
2. Click on Assessment, select start new (if there is an assessment in progress)
3. Using Keyboard, navigate to the switcher drop down list that allows you to go to FastPass
4.- open the list using space bar, up arrow to select FastPass,  space to select the option
5. Using Keyboard, navigate to the switcher drop down list that allows you to go to Assessment 
6.- Open the list using space bar, down arrow to select Assessment, Space to select the option

Screen reader reads: "select workflow list collapsed FastPass" on change from FastPass to Assessment

Note: can't repro this consistently

## Expected behavior
it should announce that the page changed to Assessment view

## Extension (please complete the following information)

- OS: [e.g. Windows/Mac] Windows 
- Version [e.g. 1.140.1] 2.1.2 
- Chrome Version [e.g 71.0] 73.0.3683.103 
- Target Page https://www.washington.edu/accesscomputing/AU/before.html

## Are you willing to submit a PR?

If asked, will you be willing to submit a PR to fix this bug?No

## Did you search for similar existing issues?

Did you search for similar issues in our github issues or on [stackoverflow](https://stackoverflow.com/questions/tagged/accessibility-insights)
Yes

### PR DESCRIPTION
**Pull request by haonliu**
#### Description of changes
Currently, the 'selected option' of the switcher does not change immediately after user input. It goes through our flux loop before updating the UI. This makes NVDA anoucing the option change incorrectly. 

Saved switcher state locally to fix the a11y issue.

#### Pull request checklist

- [x] Addresses an existing issue: Fixes #570 
- [x] Added relevant unit test for your changes. (`npm run test`)
- [x] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [x] Ran precheckin (`npm run precheckin`)
- [ ] (UI changes only) Added screenshots/GIFs to description above
- [x] (UI changes only) Verified usability with NVDA/JAWS

### CODE REVIEW

**Comment by smoralesd** [comment]
I don't see  "(UI changes only) Verified usability with NVDA/JAWS" box check... this change directly affect screen readers. It would be nice to test it and reflect it on the PR description

File: src/DetailsView/components/switcher.tsx [hunk 1]
```diff
@@ -18,17 +18,26 @@ export interface SwitcherProps {
...
             <div className="switcher-dropdown-option" aria-hidden="true">
                 {option.data && option.data.icon && <Icon iconName={option.data.icon} />}
                 <span>{option.text}</span>
             </div>
         );
-    };
+    }
 
-    const onRenderTitle = (options: IDropdownOption[]): JSX.Element => {
+    private onRenderTitle(options: IDropdownOption[]): JSX.Element {
```
Comment (smoralesd) [inline src/DetailsView/components/switcher.tsx]: Why are you changing the style of the functions here??? using the previous style let you avoid the use of `@autobind`

File: src/tests/unit/tests/DetailsView/components/switcher.test.tsx [hunk 2]
```diff
@@ -36,21 +36,20 @@ describe('Switcher', () => {
         expect(renderer.debug()).toMatchSnapshot();
     });
 
-    test('onOptionClick', () => {
+    test('onOptionChange', () => {
         actionCreatorMock
-            .setup(creator => creator.sendPivotItemClicked(DetailsViewPivotType[DetailsViewPivotType.fastPass]))
+            .setup(creator => creator.sendPivotItemClicked(DetailsViewPivotType[DetailsViewPivotType.assessment]))
```
Comment (smoralesd) [inline src/tests/unit/tests/DetailsView/components/switcher.test.tsx]: do you need to swap the states like this??? It feels like adding a change that doesn't actually affect what you're testing.

File: src/DetailsView/components/switcher.tsx (hunk 1 above)
Comment (Shobhit1) [reply src/DetailsView/components/switcher.tsx]: Is it possible to create a arrow function in our class implementations? I think he changed the `Switcher` from a function to class and thats why he changed the arrow function to a private function as well.

File: src/tests/unit/tests/DetailsView/components/switcher.test.tsx (hunk 2 above)
Comment (haonliu) [reply src/tests/unit/tests/DetailsView/components/switcher.test.tsx]: Just want to make the test scenario more clear: initial state is fastpass and user changes it to assessment.

**Comment by haonliu** [comment]
> I don't see "(UI changes only) Verified usability with NVDA/JAWS" box check... this change directly affect screen readers. It would be nice to test it and reflect it on the PR description

Yep. I've tested it but forgot to check the box.

File: src/DetailsView/components/switcher.tsx (hunk 1 above)
Comment (smoralesd) [reply src/DetailsView/components/switcher.tsx]: @Shobhit1, it is possible.

File: src/tests/unit/tests/DetailsView/components/switcher.test.tsx (hunk 2 above)
Comment (smoralesd) [reply src/tests/unit/tests/DetailsView/components/switcher.test.tsx]: Why is the reverse not good enough?

Comment (haonliu) [reply src/tests/unit/tests/DetailsView/components/switcher.test.tsx]: The initial state was set as fastPass (on line 19), so it feels more straightforward to me that we are testing state change from fastPass to assessment.

**Comment by waabid** [comment]
Could you add a screen grab from the NVDA speech viewer?
