### PR TITLE
fix: inspecting same element twice

### LINKED ISSUE #627: Inspect Element doesnt work if the same element is inspected again
## Describe the bug

**To Reproduce**

1. Go to any page with a11y issues
2. Run automated checks
3. click on one of the issues in the target page to open issue details dialog
4. Open devtools
5. Click on Inspect element
6. Select some other element in the devtools.
7. Inspect the same issue again.

## Screenshots
issue

**Expected**
The issue element should be highlighted in dev tools

**Actual**
The current selection in dev tools is not changed

### PR DESCRIPTION
**Pull request by smoralesd**
#### Description of changes

Make sure the state is always different (so we trigger the "emit change" on the store proxy side) by adding an auto increment count property to the dev tools store state.

#### Pull request checklist

- [x] Addresses an existing issue: Fixes #627 
- [x] Added relevant unit test for your changes. (`yarn test`)
- [x] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [x] Ran precheckin (`yarn precheckin`)
- [x] (UI changes only) Added screenshots/GIFs to description above
   - no UI/UX changes
- [x] (UI changes only) Verified usability with NVDA/JAWS
   - no UI/UX changes

### CODE REVIEW

File: src/background/stores/dev-tools-store.ts [hunk 1]
```diff
@@ -19,6 +19,7 @@ export class DevToolStore extends BaseStoreImpl<DevToolState> {
     public getDefaultState(): DevToolState {
         const defaultValues: DevToolState = {
             isOpen: false,
+            count: 0,
```
Comment (smoralesd) [inline src/background/stores/dev-tools-store.ts]: does it make sense to call this `eTag` and add a comment to clarify why do we need it?

Comment (peterdur) [reply src/background/stores/dev-tools-store.ts]: I think [eTag](https://en.wikipedia.org/wiki/HTTP_ETag) is not quite the right concept (it's about not doing work when the same page is requested), but agree that it would be good to have something more explicit than `count`. Maybe something like `inspectRequestId` or `distinctInspectId` or something like that?

File: src/tests/unit/tests/background/stores/dev-tools-store.test.ts [hunk 2]
```diff
@@ -57,6 +57,7 @@ describe('DevToolsStoreTest', () => {
         const exepctedState = getDefaultState();
         exepctedState.inspectElement = payload;
         exepctedState.frameUrl = null;
+        exepctedState.count = 1;
```
Comment (peterdur) [inline src/tests/unit/tests/background/stores/dev-tools-store.test.ts]: Typo: should be `expected`

File: src/common/types/store-data/idev-tool-state.d.ts [hunk 3]
```diff
@@ -4,4 +4,5 @@ export interface DevToolState {
     isOpen: boolean;
     inspectElement?: string[];
     frameUrl?: string;
+    count?: number;
```
Comment (peterdur) [inline src/common/types/store-data/idev-tool-state.d.ts]: Consider not making `count` optional in the interface, since it's already always there in non-test code (requires including it in stub in frame-url-search-initiator.test.ts)

Comment (smoralesd) [reply src/common/types/store-data/idev-tool-state.d.ts]: updated!

File: src/tests/unit/tests/background/stores/dev-tools-store.test.ts (hunk 2 above)
Comment (smoralesd) [reply src/tests/unit/tests/background/stores/dev-tools-store.test.ts]: fixed

File: src/background/stores/dev-tools-store.ts (hunk 1 above)
Comment (smoralesd) [reply src/background/stores/dev-tools-store.ts]: Updated

File: src/background/stores/dev-tools-store.ts [hunk 4]
```diff
@@ -19,6 +19,7 @@ export class DevToolStore extends BaseStoreImpl<DevToolState> {
     public getDefaultState(): DevToolState {
         const defaultValues: DevToolState = {
             isOpen: false,
+            inspectElementRequestId: 0,
```
Comment (devaradhanm) [inline src/background/stores/dev-tools-store.ts]: can we just send a message back from devtools once the inspect is successful? if inspect is successfule, background can clear the inspectedElement value rite?

Comment (smoralesd) [reply src/background/stores/dev-tools-store.ts]: That's more complex to do... I now this seems hacky, but it's way simpler
