### PR TITLE
BugFix fix details view crash when target page is closed

### LINKED ISSUE #598: Details view crashes when refresh after target page is closed
## Describe the bug

Details view crashes when refresh after target page is closed

**To Reproduce**

1. Go to any web page.
2. Click on fastPass.
3. Close the target page then refresh the details view page.
4. See error: details view is blank

## Expected behavior

details view should not crash

### PR DESCRIPTION
**Pull request by haonliu**
#### Description of changes

fix details view crash when target page is closed

#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #598 
- [ ] Added relevant unit test for your changes. (`npm run test`)
- [ ] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [ ] Ran precheckin (`npm run precheckin`)
- [ ] Added screenshots/GIFs for UI changes.

### CODE REVIEW

File: src/DetailsView/details-view-initializer.ts [hunk 1]
```diff
@@ -97,221 +98,209 @@ if (isNaN(tabId) === false) {
     chromeAdapter.getTab(
         tabId,
         (tab: Tab): void => {
```
Comment (waabid) [inline src/DetailsView/details-view-initializer.ts]: All these changes suggest to me that this may be a good time to break apart this function to a named variable ('createDefaultRenderer' potentially?) instead.

Comment (haonliu) [reply src/DetailsView/details-view-initializer.ts]: Agreed that we need a better strategy to initialize the details view page. Don't want to rush it in this PR though.

**Comment by Shobhit1** [comment]
Will this undo the fix made for: #474 ?

**Comment by haonliu** [comment]
> Will this undo the fix made for: #474 ?

No it won't.
