### PR TITLE
fix: switcher state is updated correctly (on component did update)

### LINKED ISSUE #659: Details view switcher is not updated when view changed from popup view
## Describe the bug

The details view switcher does not update when you click on fast pass or assessments in the popup view.

**To Reproduce**

1. Open popup view.
2. Click FastPass.
3. Open popup view again.
4. Click Assessment.

Note how the switcher is not updated and still says fast pass.

## Expected behavior

The switcher should state assessment when switched.

## Screenshots

switchernotupdated

## Extension (please complete the following information)

- OS: Windows
- Version 2.3.0
## Are you willing to submit a PR?

Yes

### PR DESCRIPTION
**Pull request by waabid**
#### Description of changes

A change was made such that the state is being represented in the control instead of the props for the switcher. This was due to the nature of React Flux and how it works with accessibility concerns. However, a part was missed: when props are updated, the state should be updated (we have this in previous uses of the pattern). This is _that_ change.

switchernotupdatedbugfix

#### Pull request checklist

- [x] Addresses an existing issue: Fixes #659
- [x] Added relevant unit test for your changes. (`npm run test`)
- [x] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [x] Ran precheckin (`npm run precheckin`)
- [x] (UI changes only) Added screenshots/GIFs to description above
- [n/a] (UI changes only) Verified usability with NVDA/JAWS

### CODE REVIEW

File: src/DetailsView/components/switcher.tsx [hunk 1]
```diff
@@ -27,6 +28,12 @@ export class Switcher extends React.Component<SwitcherProps, SwitcherState> {
         this.state = { selectedKey: props.pivotKey };
     }
 
+    public componentDidUpdate(prevProps: Readonly<SwitcherProps>): void {
+        if (isEqual(prevProps, this.props) === false) {
```
Comment (Shobhit1) [inline src/DetailsView/components/switcher.tsx]: nit: do we want to check for all the props and perform a deep comparison here or can it be improved by comparing some specific prop or property?
