### PR TITLE
fix: make "copy failure details" button in target page dialog work again

### LINKED ISSUE #1501: Copy failure details fail on the target page
## Describe the bug

Activating "Copy failure details" button on the target page's failure details dialog shows the "Failed to copy failure details. Please try again." toast.

**To Reproduce**

1. Go to [accessible university before](http://www.washington.edu/accesscomputing/AU/before.html)
2. Run automated checks
3. Activate any "!" icon
4. On the failure details dialog, activate "Copy failure details" button
5. Observe: the "Failed to copy failure details. Please try again." toast shows up. No details are copied to the system clipboard

## CodePen repro example

Not needed

## Expected behavior

Copy failure details should work properly

## Screenshots

01 - copy failure details on target page fails

## Extension (please complete the following information)

- OS: Windows 10 Enterprise 10.0.18362 Build 18362
- Extension Version: insider 2.10.1 (on edge dev)
- Browser Version Microsoft Edge version 79.0.294.1
- Target Page http://www.washington.edu/accesscomputing/AU/before.html

## Are you willing to submit a PR?

Yes

## Did you search for similar existing issues?

No

## Additional context

**Not** present on production

### PR DESCRIPTION
**Pull request by dbjorge**
#### Description of changes

* Adds `console.error` logging with the full error message on copy failure, for diagnosability
* Wires up `NavigatorUtils` in the target page to the dialog renderer (it was missing before)

screenshot of copying working in target page

(give an overview. Add technical description describing your changes)

#### Pull request checklist

- [x] Addresses an existing issue: Fixes #1501 
- [x] Added relevant unit test for your changes. (`yarn test`)
- [x] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [x] Ran precheckin (`yarn precheckin`)
- [x] (UI changes only) Added screenshots/GIFs to description above
- [x] (UI changes only) Verified usability with NVDA/JAWS

### CODE REVIEW

File: src/common/components/cards/card-kebab-menu-button.tsx [hunk 1]
```diff
@@ -142,6 +142,7 @@ export class CardKebabMenuButton extends React.Component<CardKebabMenuButtonProp
         try {
             await this.props.deps.navigatorUtils.copyToClipboard(text);
         } catch (error) {
+            console.error(`Failed to copy failure details: ${error}`);
```
Comment (smoralesd) [inline src/common/components/cards/card-kebab-menu-button.tsx]: should use `Logger` from `src\common\logging\logger.ts`

File: src/common/components/copy-issue-details-button.tsx [hunk 2]
```diff
@@ -40,6 +40,7 @@ export class CopyIssueDetailsButton extends React.Component<CopyIssueDetailsButt
         try {
             await this.props.deps.navigatorUtils.copyToClipboard(this.getIssueDetailsText(this.props.issueDetailsData));
         } catch (error) {
+            console.error(`Failed to copy failure details: ${error}`);
```
Comment (smoralesd) [inline src/common/components/copy-issue-details-button.tsx]: should use `Logger` from `src\common\logging\logger.ts`

File: src/tests/unit/tests/injected/visualization/drawer-provider.test.ts [hunk 3]
```diff
@@ -1,5 +1,6 @@
 // Copyright (c) Microsoft Corporation. All rights reserved.
 // Licensed under the MIT License.
+import { NavigatorUtils } from 'common/navigator-utils';
 import { IMock, Mock } from 'typemoq';
 import { BrowserAdapter } from '../../../../../common/browser-adapters/browser-adapter';
```
Comment (smoralesd) [inline src/tests/unit/tests/injected/visualization/drawer-provider.test.ts]: probably a good time to update this import paths to non-relative ones

File: src/injected/dialog-renderer.tsx [hunk 4]
```diff
@@ -82,6 +84,7 @@ export class DialogRenderer {
                 fixInstructionProcessor,
                 issueDetailsTextGenerator,
                 windowUtils: this.windowUtils,
+                navigatorUtils: this.navigatorUtils,
                 targetPageActionMessageCreator: mainWindowContext.getTargetPageActionMessageCreator(),
                 issueFilingActionMessageCreator: mainWindowContext.getIssueFilingActionMessageCreator(),
                 browserAdapter: this.browserAdapter,
```
Comment (haonliu) [inline src/injected/dialog-renderer.tsx]: I think with this change we can remove the casting on Line 93 now. I'm concerned it would cause more issue in the future. But not necessarily have to be in this PR since you did not touch that.

Comment (dbjorge) [reply src/injected/dialog-renderer.tsx]: Good point, addressed

File: src/injected/dialog-renderer.tsx [hunk 5]
```diff
@@ -82,6 +84,7 @@ export class DialogRenderer {
                 fixInstructionProcessor,
                 issueDetailsTextGenerator,
                 windowUtils: this.windowUtils,
+                navigatorUtils: this.navigatorUtils,
```
Comment (peterdur) [inline src/injected/dialog-renderer.tsx]: Would the compiler have caught this if this were `const deps: LayeredDetailsDialogDeps = { ... }` instead of `const deps = { ... } as LayeredDetailsDialogDeps`? If so, should we prefer that way?

Comment (haonliu) [reply src/injected/dialog-renderer.tsx]: I agree. we should try to avoid casting.

Comment (dbjorge) [reply src/injected/dialog-renderer.tsx]: Already resolved

File: src/tests/unit/tests/injected/visualization/drawer-provider.test.ts (hunk 3 above)
Comment (dbjorge) [reply src/tests/unit/tests/injected/visualization/drawer-provider.test.ts]: I'd rather keep those to separate PRs

File: src/common/navigator-utils.ts [hunk 6]
```diff
@@ -31,7 +31,12 @@ export class NavigatorUtils {
         return userAgent.substring(versionOffset + versionPrefix.length + 1).split(' ')[0];
     }
 
-    public copyToClipboard(data: string): Promise<void> {
-        return this.navigatorInfo.clipboard.writeText(data);
+    public async copyToClipboard(data: string): Promise<void> {
+        try {
```
Comment (smoralesd) [inline src/common/navigator-utils.ts]: is the try-catch needed?
can it be something like:
```typescript
public async copyToClipboard(data: string): Promise<void> {
   return this.navigatorInfo.clipboard.writeText(data).catch(error => {
      this.logger.error('Error during copyToClipboard: ', error);
      throw error;
   });
}
```

Comment (dbjorge) [reply src/common/navigator-utils.ts]: I've changed this because I don't think it's any worse of a solution, but I also don't think it's better than the original code using try-catch; I think this is a personal style preference for which we do not currently have a consistent team style to follow, so I feel a little bit frustrated to be spending time addressing it :(
