### PR TITLE
fix: treat non-img-tag images without role=img as implicitly decorative

### LINKED ISSUE #696: Decorative elements with a CSS background-image are reported as Meaningful when a nested element has an aria-label
## Describe the bug

Decorative elements with a CSS background-image are reported as "Meaningful" when there is a nested element (in this case a `<nav>`) with an aria-label inside of the decorative container element.

Tool guidance specifically says:
 
1. Examine each image to verify that its coded function is correct.
   - An image should be coded as meaningful if it conveys information that isn't available through other page content.
   - An image should be coded as decorative if it could be removed from the page with no impact on meaning or function.
2. Record your results:
   - Select Fail for any instances that do not meet the requirement.
   - Otherwise, select Pass. Or, after you have marked all failures, select Pass unmarked instances.

Based on the tool guidance, these elements would be marked as "Fail"s even though I believe they are Passes.

## To Reproduce
HTML structure is as follows:

```
<div id="parent-element">
   <div class="container"> 
     <!-- Static navbar -->
        <nav class="navbar navbar-default navbar-static-top" aria-label="Label for the nested element">
          ...
        </nav>
   </div>
</div>
```
CSS code is as follows:
```
 #parent-element {
    color: #FEFEFE;
    background: url(https://images.unsplash.com/photo-1547499417-61a435d27cb3?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1200&h=200&fit=crop&ixid=eyJhcHBfaWQiOjF9);
    background-repeat: repeat-x;
}
```

**Codepen Reproduction Steps**

1. Go to this [codepen](https://codepen.io/anon/pen/LoeXoV). Alternatively, create an element with a CSS background image (decorative). Inside the element, add a nested element with an aria-label
2. Run an assessment on the page (or run an assessment on this )
3. Open the Images / Image function section
4. You will then see the following for the element with the CSS background image

```
Image type: CSS background-image
Coded as: Meaningful
Accessible name: Label for the nested element
```
## Expected behavior

Since the element with the CSS background-image is decorative and is coded using a CSS background-image, I would have expected to see this scenario coded as "Decorative".

Is this a false positive?

## Are you willing to submit a PR?
Not sure how to fix.

## Did you search for similar existing issues?

Did you search for similar issues in our github issues or on [stackoverflow](https://stackoverflow.com/questions/tagged/accessibility-insights): Yes

### PR DESCRIPTION
**Pull request by dbjorge**
#### Description of changes

This PR resolves #696 according to the changes suggested by @LiLoDavis in [this comment](https://github.com/microsoft/accessibility-insights-web/issues/696#issuecomment-499595036), modulo leaving out the "omit failures of area-alt, image-alt, role-img-alt" part of the instances lists per [this comment](https://github.com/microsoft/accessibility-insights-web/issues/696#issuecomment-499624901) from @ferBonnin.

The bulk of this PR was implemented by @lisli1; I just fixed up the "meaningful images" instance lists.

In summary:
* Updates "how to test" text for **Images** requirements **Image function**, **Text alternative**, and **Images of text**.
* Changes requirements whose instance lists show "meaningful images" to treat svg/icon-font/CSS-background-image cases *without* `role="img"` as decorative, even if they have accessible text. This affects inclusion in the instance list for Images->Text alternative, Images->Images of text, Contrast->Graphics, and affects the "Coded as" column of Images->Image Function.
* Adds "ARIA role" to the information displayed in instance values in the Images->Image Function and Images->Images of text requirements

#### Screenshots

1. Screenshot of repro case from original #696 report that was previously reported as "meaningful" now being reported as "decorative":

screenshot of now-decorative repro case

2. New "How to test" text for **Image function**:

screenshot of image function how to test

3. New "How to test" text for **Text alternative**:

screenshot of text alternative how to test

4. New "How to test" text for **Images of text**:

screenshot of images of text how to test

#### Pull request checklist

- [x] Addresses an existing issue: #696
- [x] Ran `yarn fastpass`
- [x] Added/updated relevant unit test(s) (and ran `yarn test`)
- [x] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [x] PR title *AND* final merge commit title both start with a semantic tag (`fix:`, `chore:`, `feat(feature-name):`, `refactor:`). Check workflow guide at: `<rootDir>/docs/workflow.md`
- [x] (UI changes only) Added screenshots/GIFs to description above
- [x] (UI changes only) Verified usability with NVDA/JAWS

### CODE REVIEW

File: src/assessments/images/test-steps/image-function.tsx [hunk 1]
```diff
@@ -30,12 +30,14 @@ const howToTest: JSX.Element = (
         <br />
         <Markup.Emphasis>
             Notes: (1) If an image has no code to identify it as meaningful or decorative, it will
-            fail an automated check. (2) Assistive technologies will ignore any image coded as
-            decorative, even if it has an accessible name.
+            not be shown here; instead it will fail an automated check. (2) Assistive technologies
```
Comment (ferBonnin) [inline src/assessments/images/test-steps/image-function.tsx]: given that we didnt do the exclusion (don't show if it fails image-alt rule) I think we can leave 1 as it was.

Comment (dbjorge) [reply src/assessments/images/test-steps/image-function.tsx]: Updated!
