### PR TITLE
Show feature flag values when enable/disable feature

### LINKED ISSUE #629: undefined returned when enable/disable feature
## Describe the bug
undefined is returned when enable/disable feature

**To Reproduce**

1. Go to background.html.
2. Enter insigghtsFeatureFlags.enableFeature('showAllFeatureFlags')
3. See undefined logged in the console.

## Expected behavior

some useful info logged in the console instead of 'undefined'

## Screenshots
image

## Extension (please complete the following information)

- OS: Windows
- Version: any
- Browser Version: any
- Target Page: any

## Are you willing to submit a PR?

yes

### PR DESCRIPTION
**Pull request by haonliu**
#### Description of changes

Per user feedback, show feature flag values when enable/disable a feature instead of 'undefined'. Confirmed the UX with Fer.

Before:
image

After:
image

#### Pull request checklist

- [x] Addresses an existing issue: Fixes #629 
- [x] Added relevant unit test for your changes. (`npm run test`)
- [x] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [x] Ran precheckin (`npm run precheckin`)
- [x] Added screenshots/GIFs for UI changes.

### CODE REVIEW

File: src/background/feature-flags-controller.ts [hunk 1]
```diff
@@ -24,30 +24,27 @@ export class FeatureFlagsController {
...
+    public enableFeature(feature: string): FeatureFlagStoreData {
+        return this.toggleFeatureFlag(feature, true);
+    }
+
+    private toggleFeatureFlag(feature: string, enabled: boolean): FeatureFlagStoreData {
         const payload: FeatureFlagPayload = {
-            feature: feature,
-            enabled: true,
+            feature,
+            enabled,
```
Comment (lisli1) [inline src/background/feature-flags-controller.ts]: Should we not have `feature: feature, enabled: enabled`? This seems to work fine but I am wondering why we don't have to be more explicit with it.

Comment (haonliu) [reply src/background/feature-flags-controller.ts]: Both approach has pros and cons. This is more clear and concise while it is easier to rename if using ````feature: feature, enabled: enabled````.
